In [22]:
import numpy as np
import matplotlib.pyplot as plt
import os

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.decomposition import PCA

In [23]:
X = np.load("eyes_embeddings.npy")
y = np.load("eyes_labels.npy")

print("X shape:", X.shape)
print("Labels:", np.unique(y, return_counts=True))

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X shape: (30, 512)
Labels: (array(['Arched_Eyebrows', 'Narrow_Eyes'], dtype='<U15'), array([25,  5]))


In [24]:
clf = LogisticRegression(max_iter=3000)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Accuracy:", acc)

Accuracy: 0.8333333333333334


In [25]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[5 0]
 [1 0]]


In [26]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np

def evaluate_binary_task(name, show_pca=True):
    X = np.load(f"{name}_embeddings.npy")
    y = np.load(f"{name}_labels.npy")

    print(f"\n{name}")
    print("X shape:", X.shape)
    print("Labels:", np.unique(y, return_counts=True))

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    clf = LogisticRegression(max_iter=3000)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    print("Accuracy:", acc)
    print("Confusion matrix:")
    print(cm)

    if show_pca:
        pca = PCA(n_components=2)
        X_pca = pca.fit_transform(X)

        plt.figure(figsize=(6,6))
        for label in [0, 1]:
            idx = y == label
            plt.scatter(
                X_pca[idx, 0],
                X_pca[idx, 1],
                label="Positive" if label == 1 else "Negative",
                alpha=0.5
            )

        plt.legend()
        plt.title(f"{name} Embeddings (PCA)")
        plt.xlabel("PC1")
        plt.ylabel("PC2")
        plt.show()

    return acc


In [27]:
results = {}

for fname in os.listdir("."):
    if fname.endswith("_embeddings.npy"):
        task_name = fname.replace("_embeddings.npy", "")
        try:
            acc = evaluate_binary_task(task_name, show_pca=False)
            results[task_name] = acc
        except Exception as e:
            print(f"Skipping {task_name}: {e}")



nose
X shape: (42, 512)
Labels: (array(['Big_Nose', 'Pointy_Nose'], dtype='<U11'), array([16, 26]))
Accuracy: 0.5555555555555556
Confusion matrix:
[[1 2]
 [2 4]]

eyes
X shape: (30, 512)
Labels: (array(['Arched_Eyebrows', 'Narrow_Eyes'], dtype='<U15'), array([25,  5]))
Accuracy: 0.8333333333333334
Confusion matrix:
[[5 0]
 [1 0]]

face
X shape: (34, 512)
Labels: (array(['Eyeglasses', 'Oval_Face', 'Pale_Skin'], dtype='<U10'), array([ 2, 29,  3]))
Accuracy: 0.7142857142857143
Confusion matrix:
[[5 1]
 [1 0]]

face_Pale_Skin
X shape: (34, 512)
Labels: (array([0, 1]), array([31,  3]))
Accuracy: 0.8571428571428571
Confusion matrix:
[[6 0]
 [1 0]]

face_Oval_Face
X shape: (34, 512)
Labels: (array([0, 1]), array([ 5, 29]))
Accuracy: 0.7142857142857143
Confusion matrix:
[[0 1]
 [1 5]]

cheeks_Rosy_Cheeks
X shape: (46, 512)
Labels: (array([0, 1]), array([38,  8]))
Accuracy: 0.6
Confusion matrix:
[[6 2]
 [2 0]]

cheeks
X shape: (46, 512)
Labels: (array(['High_Cheekbones', 'Rosy_Cheeks'], dtype=

/Users/chris.shia/Documents/GitHub/CV-Final-Project/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:620: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
